@echo off
title AHhaHAHhahAHhhaHAhaHAH
color 
cls
:init
start pop_up.bat
echo HhAHhahAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
echo hAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
echo AHahHAHhAHhahAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
color 28
echo HhAHhahAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
echo hAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
echo AHahHAHhAHhahAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
color 52
echo HhAHhahAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
echo hAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
echo AHahHAHhAHhahAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
color 39
echo HhAHhahAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
echo hAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
echo AHahHAHhAHhahAHAhahahHhahHAHahHAHhhhHhahahHAHhahHAHhaHA
color 1f
goto init