
CREATE TABLE PUBLIC.TBLEXAMPLE(
	KEY1 CHARACTER VARYING(10) NOT NULL,
	KEY2 CHARACTER VARYING(14) NOT NULL,

	VALUE1 CHARACTER VARYING(20),
	VALUE2 CHARACTER VARYING(20) NOT NULL,

	CONSTRAINT TBLEXAMPLE_PKEY PRIMARY KEY (KEY1, KEY2)
)

CREATE TRIGGER TBLEXAMPLE_AFTER
AFTER INSERT
ON PUBLIC.TBLEXAMPLE
FOR EACH ROW
EXECUTE PROCEDURE PUBLIC.NOTIFY();


CREATE OR REPLACE FUNCTION PUBLIC.NOTIFY() RETURNS trigger AS
$BODY$
BEGIN
	PERFORM pg_notify('myEvent', row_to_json(NEW)::text);
	RETURN new;
END;
$BODY$
LANGUAGE 'plpgsql' VOLATILE COST 100;


/* INSERT INTO PUBLIC.TBLEXAMPLE(KEY1, KEY2, VALUE1, VALUE2) VALUES ('k1', 'k2', 'v1', 'v2'); */